# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    networks: 
      - grid_network
    ports:
      - 27017:27017
    volumes:
      - grid_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  server-grpc:
    image: service:grid
    restart: always
    networks:
      - grid_network
    ports:
      - 9999:9999
    environment:
      DB_HOSTNAME: mongo
      DB_PORT: 27017
  server-gateway:
    image: service:gateway
    restart: always
    networks:
      - grid_network
    ports:
      - 8888:8888

networks:
  grid_network:
    name: grid_network
volumes: 
  grid_data:
    external: true