# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    networks: 
      - test_network
    ports:
      - 27017:27017
    volumes:
      - test_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  test_network:
    name: test_network
volumes: 
  test_data:
    external: false