# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    networks: 
      - test_network
    ports:
      - 27017:27017
    volumes:
      - test_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  server-grpc:
    image: service:grid
    restart: always
    networks:
      - test_network
    ports:
      - 9999:9999
    environment:
      DB_HOSTNAME: mongo
      DB_PORT: 27017
  server-gateway:
    image: service:gateway
    restart: always
    networks:
      test_network
    ports:
      - 8888:8888

  mongo-console:
    image: mongo-express
    restart: always
    networks:
      - test_network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  test_network:
    name: test_network
volumes: 
  test_data:
    external: false
    