# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    networks: 
      - grid_network
    volumes:
      - grid_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  grid:
    image: service:grid
    restart: always
    networks:
      - grid_network
    ports:
      - 8888:8888
    environment:
      DB_HOSTNAME: mongo
      DB_PORT: 27017
  frontend:
    image: service:front
    restart: always
    networks:
      - grid_network
    ports:
      - 5000:5000
    environment:
      GRID_HOSTNAME: grid


networks:
  grid_network:
    name: grid_network
volumes: 
  grid_data:
    external: true