name: Backend tests on push from dev

on:
  push:
    branches: [ dev ]

jobs:
  grid-storage-npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install
        run: cd backend/services/grid-storage && npm ci
      - name: Launch local mongo db
        run: |
          docker network create test_network
          docker compose --file backend/services/compose/compose-stack-test.yml up --detach
      - name: Run tests
        run: |
          cd backend/services/grid-storage && npm test
      - name: Stop local containers
        run: |
          docker compose --file backend/services/compose/compose-stack-test.yml down
  grid-gateway-npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install
        run: cd backend/services/gateway && npm ci      
      - name: Run tests
        run: cd backend/services/gateway && npm test

        