name: Backend tests on push from dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  grid-storage-npm-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install
        run: cd backend/services/grid-storage && npm ci
      - name: Launch local mongo db
        run: |
          docker volume create test_data
          docker compose --file backend/services/mongo/mongo-stack.yml up --detach
      - name: Run tests
        run: cd backend/services/grid-storage && npm test
      - name: Stop local mongo db
        run: docker compose --file backend/services/mongo/mongo-stack.yml down
        